Repository aws/jsii-rosetta, pull requests merged in 2024-05, with the labels that each got.

#1275 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1276 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#1277 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#1278 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1279 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#1280 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1281 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1282 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1283 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1285 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1284 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1286 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1287 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1288 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1289 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1292 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1291 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1290 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1294 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1295 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1296 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1298 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1297 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1299 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1300 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1301 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1302 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1303 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1305 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1304 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1306 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1307 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1308 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1293 fix: error TS2339: Property 'VISUALIZE' does not exist on type 'typeof TargetLanguage'
  .projen/tasks.json
  .projenrc.ts
  src/languages/target-language.ts
  tsconfig.dev.json
  tsconfig.json
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#1310 fix: error TS2339: Property 'VISUALIZE' does not exist on type 'typeof TargetLanguage' (backport #1293)
  .projen/tasks.json
  .projenrc.ts
  src/languages/target-language.ts
  tsconfig.dev.json
  tsconfig.json
Labels: auto-approve, backport

#1309 fix: error TS2339: Property 'VISUALIZE' does not exist on type 'typeof TargetLanguage' (backport #1293)
  .projen/tasks.json
  .projenrc.ts
  src/languages/target-language.ts
  tsconfig.dev.json
  tsconfig.json
Labels: auto-approve, backport

#1311 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1312 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1313 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1314 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1315 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1316 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1317 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1319 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1320 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1323 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1324 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1325 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1326 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1327 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1328 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1329 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1330 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1331 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1318 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1321 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1332 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1333 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1334 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1335 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1336 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1337 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1338 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1339 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1340 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1343 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1341 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1342 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1344 chore(ci): fix backport workflow is failing when PR is not yet merged
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: bug

#1346 chore(ci): fix backport workflow is failing when PR is not yet merged (backport #1344)
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: auto-approve, backport

#1345 chore(ci): fix backport workflow is failing when PR is not yet merged (backport #1344)
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: auto-approve, backport

#1347 chore(ci): update backport action to latest version
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#1348 chore(ci): update backport action to latest version (backport #1347)
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: auto-approve, backport

#1349 chore(ci): update backport action to latest version (backport #1347)
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: auto-approve, backport

#1351 chore(ci): don't run backport action on backport PRs
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#1352 chore(ci): don't run backport action on backport PRs (backport #1351)
  .github/workflows/backport.yml
  projenrc/pull-request-backport.ts
Labels: auto-approve, backport

#1355 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1356 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1358 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1359 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1361 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1362 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1363 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1364 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1365 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1366 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1360 chore: remove unsupported version from readme
  README.md
Labels: documentation, backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#1368 chore: remove unsupported version from readme (backport #1360)
  README.md
Labels: auto-approve, backport

#1367 chore: remove unsupported version from readme (backport #1360)
  README.md
Labels: auto-approve, backport

#1369 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1370 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1373 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1371 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1372 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1374 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1375 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1376 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1378 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1379 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1380 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1381 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1382 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1384 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1383 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1385 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1387 chore: restore ability to release maintenance version lines (backport #1386)
  .backportrc.json
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/release.ts
  projenrc/support.ts
  projenrc/tag-release.ts
  projenrc/upgrade-dependencies.ts
  releases.json
  yarn.lock
Labels: auto-approve, backport

#1388 chore: restore ability to release maintenance version lines (backport #1386)
  .backportrc.json
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/release.ts
  projenrc/support.ts
  projenrc/tag-release.ts
  projenrc/upgrade-dependencies.ts
  releases.json
  yarn.lock
Labels: auto-approve, backport

#1389 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1390 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1391 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1392 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1394 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1393 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1395 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1396 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1398 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1399 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1400 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1401 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1402 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1403 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1404 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1405 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1406 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1407 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1408 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1409 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1411 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1412 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1410 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1413 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1414 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1415 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1416 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1417 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1418 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1419 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1420 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1421 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1422 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1423 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1424 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1425 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1426 chore(deps): upgrade dependencies
  .projen/tasks.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1427 chore(deps): upgrade dependencies
  .projen/tasks.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1430 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1428 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1429 chore(deps): upgrade dependencies
  .projen/tasks.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1431 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1432 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve
