Repository aws/jsii-rosetta, pull requests merged in 2024-08, with the labels that each got.

#1699 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1700 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1701 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1702 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1703 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1704 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1705 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1706 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1707 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1708 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1709 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1710 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1711 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1712 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1713 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1714 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1715 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1716 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1718 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1719 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1720 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1721 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1717 chore(ci): use pr backports from upstream projen
  .github/workflows/backport.yml
  .projenrc.ts
  projenrc/pull-request-backport.ts
Labels: backport-to-maintenance/v5.3

#1723 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1724 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1725 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1726 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1727 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1728 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1729 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1730 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1731 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1732 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1733 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1734 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1735 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1736 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1737 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1738 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1739 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1740 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1741 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1743 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1744 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1745 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1746 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1747 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1748 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1749 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1750 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1751 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1752 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1753 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1754 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1755 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1756 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1757 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1758 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1759 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1760 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1761 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1762 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1763 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1764 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1765 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1766 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1767 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1768 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1770 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1771 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1772 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1773 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1774 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1775 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1776 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1779 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1781 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1783 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1784 chore(deps): upgrade dependencies
  .gitattributes
  package.json
  yarn.lock
Labels: auto-approve

#1785 chore(deps): upgrade dependencies
  .gitattributes
  package.json
  yarn.lock
Labels: auto-approve

#1786 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1787 chore: config backport to support ts5.5 release (backport #1778)
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.4.yml
  .github/workflows/auto-tag-releases-v5.4.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  README.md
  projenrc/support.ts
  releases.json
  src/renderer.ts
  test/translations/classes/class_with_extends_and_implements.py
  test/translations/classes/constructor_with_optional_params.cs
  test/translations/classes/constructor_with_optional_params.py
Labels: auto-approve, backport

#1789 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1790 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1791 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1792 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1793 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1794 chore(deps): upgrade dependencies
  .gitattributes
  package.json
  yarn.lock
Labels: auto-approve

#1795 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1796 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1797 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1798 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1799 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1800 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1801 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1802 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1803 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1805 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1806 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1807 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1808 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1810 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1809 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1811 fix: extracting snippets cause large spike in file system access
  src/commands/transliterate.ts
  src/jsii/assemblies.ts
  src/snippet.ts
Labels: backport-to-maintenance/v5.3, backport-to-maintenance/v5.4

#1812 fix: extracting snippets cause large spike in file system access (backport #1811)
  src/commands/transliterate.ts
  src/jsii/assemblies.ts
  src/snippet.ts
Labels: auto-approve, backport

#1813 fix: extracting snippets cause large spike in file system access (backport #1811)
  src/commands/transliterate.ts
  src/jsii/assemblies.ts
  src/snippet.ts
Labels: auto-approve, backport

#1814 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1815 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1816 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1817 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1818 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1819 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1821 fix(transliterate): installing snippet dependencies can fail due to scripts (backport #1820)
  src/snippet-dependencies.ts
  test/rosetta-translator.test.ts
Labels: auto-approve, backport

#1822 fix(transliterate): installing snippet dependencies can fail due to scripts (backport #1820)
  src/snippet-dependencies.ts
  test/rosetta-translator.test.ts
Labels: auto-approve, backport

#1823 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1824 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1825 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1826 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1827 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1828 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1829 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1832 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1833 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1804 chore: update release instructions
  .projenrc.ts
Labels: backport-to-maintenance/v5.3, backport-to-maintenance/v5.4

#1835 chore: update release instructions (backport #1804)
  .projenrc.ts
Labels: auto-approve, backport

#1836 chore: update release instructions (backport #1804)
  .projenrc.ts
Labels: auto-approve, backport

#1837 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1838 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1839 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve
