Repository aws/jsii-rosetta, pull requests merged in 2024-09, with the labels that each got.

#1840 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1841 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1842 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1843 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1844 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1845 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#227 feat: add `--language` option to `snippet` and `markdown` commands
  src/languages/index.ts
  src/main.ts
  test/languages/index.test.ts
Labels: backport-to-maintenance/v5.3, backport-to-maintenance/v5.4

#1846 feat: add `--language` option to `snippet` and `markdown` commands (backport #227)
  src/languages/index.ts
  src/main.ts
  test/languages/index.test.ts
Labels: auto-approve, backport

#1847 feat: add `--language` option to `snippet` and `markdown` commands (backport #227)
  src/languages/index.ts
  src/main.ts
  test/languages/index.test.ts
Labels: auto-approve, backport

#1831 chore(deps): upgrade dependencies
  .projenrc.ts
  .vscode/settings.json
  package.json
  src/markdown/xml-comment-renderer.ts
  test/commands/extract.test.ts
  test/markdown/xmldoccomments.test.ts
  yarn.lock
Labels: auto-approve

#1834 chore(deps): upgrade dependencies
  .projenrc.ts
  .vscode/settings.json
  package.json
  src/markdown/xml-comment-renderer.ts
  test/commands/extract.test.ts
  test/markdown/xmldoccomments.test.ts
  yarn.lock
Labels: auto-approve

#1830 chore(deps): upgrade dependencies
  .projenrc.ts
  .vscode/settings.json
  package.json
  src/markdown/xml-comment-renderer.ts
  test/commands/extract.test.ts
  test/markdown/xmldoccomments.test.ts
  yarn.lock
Labels: auto-approve

#1848 chore(deps): upgrade projen dependencies
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  projenrc/build-workflow.ts
  projenrc/release.ts
  yarn.lock
Labels: auto-approve

#1849 chore(deps): upgrade projen dependencies (backport #1848)
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  projenrc/build-workflow.ts
  projenrc/release.ts
  yarn.lock
Labels: auto-approve, backport

#1850 chore(deps): upgrade projen dependencies (backport #1848)
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  projenrc/build-workflow.ts
  projenrc/release.ts
  yarn.lock
Labels: auto-approve, backport

#1851 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1852 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1853 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1854 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1855 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1856 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1857 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1858 chore(deps): upgrade dependencies
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  yarn.lock
Labels: auto-approve

#1859 chore(deps): upgrade dependencies
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  yarn.lock
Labels: auto-approve

#1860 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1861 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1862 chore(deps): upgrade dependencies
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  yarn.lock
Labels: auto-approve

#1866 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1867 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1868 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1869 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1870 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1871 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1872 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1873 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1874 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1875 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1876 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1877 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1878 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1879 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1880 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1881 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1882 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1883 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1884 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1885 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1886 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1887 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1888 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1889 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1890 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1891 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1892 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1893 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1894 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1895 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1896 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1897 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1898 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1899 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1900 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1901 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1902 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1863 chore(deps): upgrade dependencies
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  yarn.lock
Labels: auto-approve

#1864 chore(deps): upgrade dependencies
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  yarn.lock
Labels: auto-approve

#1903 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1904 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1865 chore(deps): upgrade dependencies
  .github/workflows/upgrade-jsii-main.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.4.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  package.json
  yarn.lock
Labels: auto-approve

#1905 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1906 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1907 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1908 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1909 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1910 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1911 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1912 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1913 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1914 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1915 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1916 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1917 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1918 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1919 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1920 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1921 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1922 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1923 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1926 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1927 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1928 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1929 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1930 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1931 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1932 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1933 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1934 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1935 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1936 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1937 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1938 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1939 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1940 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1941 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1942 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1943 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve
