Repository aws/jsii-rosetta, pull requests merged in 2024-07, with the labels that each got.

#1593 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1594 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1580 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1576 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1595 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1596 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1597 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1598 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1599 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1600 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1601 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1602 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1603 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1604 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1605 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1606 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1607 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1608 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1609 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1610 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1611 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1612 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1613 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1615 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1616 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1618 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1619 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1620 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1621 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1622 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1623 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1624 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1625 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1626 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1627 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1628 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1629 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1630 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1631 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1632 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1633 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1634 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1635 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1636 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1637 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1638 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1639 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1640 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1641 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1642 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1643 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1644 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1645 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1646 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1647 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1648 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1649 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1650 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1651 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1653 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1655 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1657 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1658 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1659 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1660 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1661 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1662 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1663 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1664 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1665 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1666 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1652 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1667 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1668 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1669 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1670 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1671 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1672 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1673 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1675 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1676 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1677 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1678 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1679 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1680 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1681 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1682 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1683 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1685 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1687 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1688 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1686 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1684 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1689 chore: fix ci PRs might get merged with failing tests
  .github/workflows/build.yml
  projenrc/build-workflow.ts
Labels: backport-to-maintenance/v5.3

#1690 chore: fix ci PRs might get merged with failing tests (backport #1689)
  .github/workflows/build.yml
  projenrc/build-workflow.ts
Labels: auto-approve, backport

#1691 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1692 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1693 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1694 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1695 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1696 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1697 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1698 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve
