Repository aws/jsii-rosetta, pull requests merged in 2024-04, with the labels that each got.

#1077 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1079 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1078 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1080 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1081 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1082 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1083 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1084 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1085 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1087 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1086 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1088 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1090 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1091 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1093 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1092 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1094 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1095 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1096 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1097 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1098 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1100 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1101 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1102 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1103 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1104 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1105 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1106 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1107 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1108 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1109 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1111 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projenrc.ts
  README.md
  package.json
  projenrc/support.ts
  releases.json
  yarn.lock
Labels: auto-approve

#1112 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1114 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1115 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1117 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1118 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1119 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1120 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1122 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1121 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1123 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1124 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1125 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1126 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1127 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1128 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1129 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1130 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1131 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1132 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1133 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1134 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1135 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1136 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1137 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1138 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1139 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1141 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1140 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1142 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1143 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1144 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1145 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1146 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1147 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1148 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1149 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1151 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1150 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1152 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1113 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projenrc.ts
  README.md
  package.json
  projenrc/support.ts
  releases.json
  yarn.lock
Labels: auto-approve

#1116 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/upgrade-jsii-maintenance-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projenrc.ts
  README.md
  package.json
  projenrc/support.ts
  releases.json
  yarn.lock
Labels: auto-approve

#1153 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1154 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1155 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1157 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1158 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1159 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1160 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1163 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1164 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1165 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1166 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1167 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1169 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1168 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1162 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1171 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1172 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1176 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1174 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1175 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1178 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1180 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1181 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1182 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1183 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1184 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1185 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1186 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1187 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1188 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1189 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1190 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1191 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1192 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1193 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1194 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1195 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1196 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1197 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1199 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1200 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1201 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1202 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1205 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1203 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1206 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1204 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1207 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1209 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1208 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1210 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1211 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1212 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1214 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1213 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1215 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1216 fix: processing example is failing when example contains jsdoc annotated export (backport #1170)
  src/fixtures.ts
  test/fixtures.test.ts
Labels: auto-approve, backport

#1217 fix: processing example is failing when example contains jsdoc annotated export (backport #1170)
  src/fixtures.ts
  test/fixtures.test.ts
Labels: auto-approve, backport

#1218 fix: processing example is failing when example contains jsdoc annotated export (backport #1170)
  src/fixtures.ts
  test/fixtures.test.ts
Labels: auto-approve, backport

#1219 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1220 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1221 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1222 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1223 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1227 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1228 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1229 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1230 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1225 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1231 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1232 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1233 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1234 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1235 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1236 chore(deps): upgrade jsii & typescript
  yarn.lock
Labels: auto-approve

#1237 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1238 fix: 'TargetLanguage' has no exported member 'VISUALIZE'
  src/languages/target-language.ts
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.1, backport-to-maintenance/v5.3
